# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ESLint

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install -g eslint
    - run: npm install -g eslint-plugin-cypress --save-dev
    - name: Check Directory
      run:  echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
    - name: Run ESLint
      run: eslint $GITHUB_WORKSPACE/source $GITHUB_WORKSPACE/cypress/integration/unit_tests $GITHUB_WORKSPACE/cypress/integration/automated_user_testing --ext .js
