# This is a basic workflow to help you get started with Actions

name: JSDOCS

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types: [ closed ]
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: Run JSDocs
      run: npx jsdoc source/js --verbose -d ./docs/jsdocs
    - name: Push to Github
      run: |
        git remote set-url origin https://github.com/samliu000/cse110-w21-group16.git
        git status
        git add docs/jsdocs
        git commit -m "Modifying jsdocs"
        git push origin main
