name: Cypress tests
on:
  pull_request:
    branches: [ main ]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Instrument Code
        run: |
          npm install -g nyc
          npx nyc instrument --compact=false source source/instrumented
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/unit_tests/timer_tests.js
      
      
