name: Cypress Tests
# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm install -g cypress
      - run: npm install -g nyc

      - name: Run Cypress
      - run: npx nyc instrument --compact=false source source/instrumented
      - run: npx cypress run --spec cypress/integration/unit_tests/timer_tests.js 
