name: Cypress tests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Instrument Code
        run: |
          rm -rf source/instrumented
          cp source/instrumentedIndex/index.html source/instrumented
          npx nyc instrument --compact=false source source/instrumented
      - name: Cypress run
        run: |
          npx cypress run --spec cypress/integration/unit_tests/*.js
      - name: Code Coverage
        run: |
          npx merge-cypress-jest-coverage
