name: Cypress Tests
# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: |
          npm ci
          npm run build --if-present
          npm install -g cypress
          npm install nyc
      - name: Run Cypress
        run: |
          npx nyc instrument --compact=false source source/instrumented
          run: npx cypress run --spec cypress/integration/unit_tests/timer_tests.js 
